# ==========================
# Configuración de Office Modular Script
# ==========================

# --- Versiones de Office soportadas ---
# Cada clave es el nombre visible de la versión.
# product_id y channel se usan para generar el XML de instalación.
office_versions:
  Office Standard 2013:
    product_id: StandardRetail
    channel: Current
  Office Professional Plus 2013:
    product_id: ProplusRetail
    channel: Current
  Office Standard 2016:
    product_id: StandardRetail
    channel: Current
  Office Professional Plus 2016:
    product_id: ProplusRetail
    channel: Current
  Office Standard 2019:
    product_id: Standard2019Volume
    channel: PerpetualVL2019
  Office Professional Plus 2019:
    product_id: ProPlus2019Volume
    channel: PerpetualVL2019
  Office LTSC Standard 2021:
    product_id: Standard2021Volume
    channel: PerpetualVL2021
  Office LTSC Professional Plus 2021:
    product_id: ProPlus2021Volume
    channel: PerpetualVL2021
  Office LTSC Standard 2024:
    product_id: Standard2024Volume
    channel: PerpetualVL2024
  Office LTSC Professional Plus 2024:
    product_id: ProPlus2024Volume
    channel: PerpetualVL2024
  Office 365 HomePremium - Current:
    product_id: O365HomePremRetail
    channel: Current
  Office 365 Apps for business - Current:
    product_id: O365BusinessRetail
    channel: Current
  Office 365 Apps for business - MonthlyEnterprise:
    product_id: O365BusinessRetail
    channel: MonthlyEnterprise
  Office 365 Apps for business - SemiAnnual:
    product_id: O365BusinessRetail
    channel: SemiAnnual
  Office 365 Apps for enterprise - Current:
    product_id: O365ProPlusRetail
    channel: Current
  Office 365 Apps for enterprise - MonthlyEnterprise:
    product_id: O365ProPlusRetail
    channel: MonthlyEnterprise
  Office 365 Apps for enterprise - SemiAnnual:
    product_id: O365ProPlusRetail
    channel: SemiAnnual

# --- Aplicaciones disponibles por versión ---
# Cada clave es una versión de Office y la lista son las apps seleccionables.
office_apps:
  Office Standard 2013:
    - Word
    - Excel
    - PowerPoint
    - Outlook
    - OneNote
    - Publisher
    - Groove
  Office Professional Plus 2013:
    - Word
    - Excel
    - PowerPoint
    - Outlook
    - OneNote
    - Publisher
    - Access
    - InfoPath
    - Lync
    - Groove
  Office Standard 2016:
    - Word
    - Excel
    - PowerPoint
    - Outlook
    - OneNote
    - Publisher
    - OneDrive
    - Groove
  Office Professional Plus 2016:
    - Word
    - Excel
    - PowerPoint
    - Outlook
    - OneNote
    - Publisher
    - OneDrive
    - Access
    - Lync
    - Groove
  Office Standard 2019:
    - Word
    - Excel
    - PowerPoint
    - Outlook
    - OneNote
    - Publisher
    - OneDrive
    - Groove
  Office Professional Plus 2019:
    - Word
    - Excel
    - PowerPoint
    - Outlook
    - OneNote
    - Publisher
    - OneDrive
    - Access
    - Lync
    - Groove
  Office LTSC Standard 2021:
    - Word
    - Excel
    - PowerPoint
    - Outlook
    - OneNote
    - Publisher
    - OneDrive
  Office LTSC Professional Plus 2021:
    - Word
    - Excel
    - PowerPoint
    - Outlook
    - OneNote
    - Publisher
    - OneDrive
    - Access
    - Teams
    - Lync
  Office LTSC Standard 2024:
    - Word
    - Excel
    - PowerPoint
    - Outlook
    - OneNote
    - OneDrive
  Office LTSC Professional Plus 2024:
    - Word
    - Excel
    - PowerPoint
    - Outlook
    - OneNote
    - OneDrive
    - Access
    - Lync
  Office 365 HomePremium - Current:
    - Word
    - Excel
    - PowerPoint
    - Outlook
    - OneNote
    - Publisher
    - Access
    - OneDrive
  Office 365 Apps for business - Current:
    - Word
    - Excel
    - PowerPoint
    - Outlook
    - OneNote
    - Teams
    - Publisher
    - Access
    - Lync
    - OneDrive
    - Groove
  Office 365 Apps for business - MonthlyEnterprise:
    - Word
    - Excel
    - PowerPoint
    - Outlook
    - OneNote
    - Teams
    - Publisher
    - Access
    - Lync
    - OneDrive
    - Groove
  Office 365 Apps for business - SemiAnnual:
    - Word
    - Excel
    - PowerPoint
    - Outlook
    - OneNote
    - Teams
    - Publisher
    - Access
    - Lync
    - OneDrive
    - Groove
  Office 365 Apps for enterprise - Current:
    - Word
    - Excel
    - PowerPoint
    - Outlook
    - OneNote
    - Teams
    - Publisher
    - Access
    - Lync
    - OneDrive
    - Groove
  Office 365 Apps for enterprise - MonthlyEnterprise:
    - Word
    - Excel
    - PowerPoint
    - Outlook
    - OneNote
    - Teams
    - Publisher
    - Access
    - Lync
    - OneDrive
    - Groove
  Office 365 Apps for enterprise - SemiAnnual:
    - Word
    - Excel
    - PowerPoint
    - Outlook
    - OneNote
    - Teams
    - Publisher
    - Access
    - Lync
    - OneDrive
    - Groove

# --- Idiomas disponibles ---
# Clave: nombre visible, Valor: código de idioma usado en el XML de configuración.
languages:
  Afrikaans: af-ZA
  Albanés: sq-AL
  Árabe: ar-SA
  Armenio: hy-AM
  Asamés: as-IN
  Azerbaiyano (Latino): az-Latn-AZ
  Bengalí (Bangladesh): bn-BD
  Bengalí (India): bn-IN
  Vasco: eu-ES
  Bosnio (Latino): bs-latn-BA
  Búlgaro: bg-BG
  Catalán: ca-ES
  Catalán (Valencia): ca-ES-valencia
  Chino (Simplificado): zh-CN
  Chino (Tradicional): zh-TW
  Croata: hr-HR
  Checo: cs-CZ
  Danés: da-DK
  Neerlandés: nl-NL
  Inglés: en-US
  Inglés (Reino Unido): en-GB
  Estonio: et-EE
  Finés: fi-FI
  Francés: fr-FR
  Francés (Canadá): fr-CA
  Gallego: gl-ES
  Georgiano: ka-GE
  Alemán: de-DE
  Griego: el-GR
  Guyaratí: gu-IN
  Hausa: ha-Latn-NG
  Hebreo: he-IL
  Hindi: hi-IN
  Húngaro: hu-HU
  Islandés: is-IS
  Igbo: ig-NG
  Indonesio: id-ID
  Irlandés: ga-IE
  Xhosa: xh-ZA
  Zulú: zu-ZA
  Italiano: it-IT
  Japonés: ja-JP
  Canarés: kn-IN
  Kazajo: kk-KZ
  Kinyarwanda: rw-RW
  Suajili: sw-KE
  Konkani: kok-IN
  Coreano: ko-KR
  Kirguís: ky-KG
  Letón: lv-LV
  Lituano: lt-LT
  Luxemburgués: lb-LU
  Macedonio (Macedonia del Norte): mk-MK
  Malayo (Latino): ms-MY
  Malayalam: ml-IN
  Maltés: mt-MT
  Maorí: mi-NZ
  Maratí: mr-IN
  Nepalí: ne-NP
  Noruego Bokmål: nb-NO
  Noruego Nynorsk: nn-NO
  Odia: or-IN
  Pastún: ps-AF
  Persa: fa-IR
  Polaco: pl-PL
  Portugués (Portugal): pt-PT
  Portugués (Brasil): pt-BR
  Panyabí (Gurmukhi): pa-IN
  Rumano: ro-RO
  Romanche: rm-CH
  Ruso: ru-RU
  Gaélico escocés: gd-GB
  Serbio (Cirílico, Serbia): sr-cyrl-RS
  Serbio (Latino, Serbia): sr-latn-RS
  Serbio (Cirílico, Bosnia y Herzegovina): sr-cyrl-BA
  Sesotho sa Leboa: nso-ZA
  Setsuana: tn-ZA
  Cingalés: si-LK
  Eslovaco: sk-SK
  Esloveno: sl-SI
  Español: es-ES
  Español (México): es-MX
  Sueco: sv-SE
  Tamil: ta-IN
  Tártaro (Cirílico): tt-RU
  Telugu: te-IN
  Tailandés: th-TH
  Turco: tr-TR
  Ucraniano: uk-UA
  Urdu: ur-PK
  Uzbeko (Latino): uz-Latn-UZ
  Vietnamita: vi-VN
  Galés: cy-GB
  Wolof: wo-SN
  Yoruba: yo-NG