python -m nuitka main.py ^
--standalone ^
--enable-plugin=tk-inter ^
--windows-icon-from-ico=icon.ico ^
--include-data-file=config.yaml=config.yaml ^
--include-package=core ^
--include-package=gui ^
--include-package=scripts ^
--include-module=utils ^
--include-package=scrapy ^
--include-package=scrapy.spiders ^
--include-package=scrapy.spiderloader ^
--include-package=scrapy.utils ^
--include-package=scrapy.crawler ^
--include-package=scrapy.selector ^
--include-package=scrapy.link ^
--include-package=scrapy.downloadermiddlewares ^
--include-package=scrapy.pipelines ^
--include-package=scrapy.extensions ^
--include-package=scrapy.core ^
--include-package=scrapy.settings ^
--include-package=scrapy.logformatter ^
--nofollow-import-to=unittest,doctest ^
--company-name="Rodri082" ^
--product-name="ManagerOfficeScriptTool" ^
--file-version=5.0.0.0 ^
--product-version=5.0.0.0 ^
--file-description="Herramienta ManagerOfficeScriptTool" ^
--copyright="Licencia MIT © 2024 Rodri082" ^
--windows-uac-admin ^
--output-dir=build ^
--output-filename=ManagerOfficeScriptTool.exe ^
--msvc=latest ^
--lto=yes ^
--report=build/compilacion.xml